#!/bin/bash

if [ -z "$1" ] ; then
    echo
    echo "Error:  Missing <version>"
    echo
    echo "Usage:  gh-release <version>"
    echo
    exit 1
fi

version="$1"

gh release create "$version" \
  ../archive/x86_64-glibc217-toolchain.tar.xz \
    --title "GCC 5 + glibc 2.17 Toolchain (x86_64)" \
    --notes "Legacy x86_64 toolchain with glibc 2.17 and GCC 5.x, runtime-enabled. Includes full sysroot.  See README for usage."

#
